#!/bin/bash

source scripts/nc.so
#======
#The main menu of the sta_nu.
menu(){
	if [[ "$sta_nu" = "0" ]]
	then
	echo
		echo -e "\t\t\t\e[34m= SERVICE PORT MONITOR =\e[0m"
		echo
		echo -e "\t\t    \e[33m| \t    1.Port Monitor     \t    |\e[0m"
		echo
	else
	echo
		echo -e "\t\t\t\e[5;31m= MONITOR IS RUNNNING =\e[0m"
		echo
                echo -e "\t\t    \e[33m| \t    1.Quit The Monitor \t    |\e[0m"
                echo
        fi
	echo -e "\t\t    \e[34m| \t    2.See The Log File \t    |\e[0m"
	echo
	echo -e "\t\t    \e[33m| \t    Q.Exit             \t    |\e[0m"
	echo
}
#======
sta_nu=0
while true
do
	clear
	menu 
	read -p "Please input the number:" choice
	case $choice in
	1)	
		if [[ "$sta_nu" = "0" ]]
		then
			echo
			read -p "Please input the IP:" ipaddr
			echo
			read -p "Please input the port:" port
			echo
			read -p "Front or Background [F/B]?" fb
			case $fb in
			F|f)
				nc_front $ipaddr $port
				;;
			b|B)
				(nc_back $ipaddr $port)&
				sta_nu=1
				;;
			*)
				echo ""
				;;
			esac
		elif [[ "$sta_nu" = "1" ]]
		then
			pro_u=`jobs -p`
			kill -9 $pro_u
			sta_nu=0
			date +%F_%k:%M:%S_Monitor_down >>"$log_name".txt
                        echo "Port interrupt for $time_down seconds befor quit." >>"$log_name".txt
                        echo "The port had down $time_down seconds befor quit."
                        echo "--------------------" >> "$log_name".txt
		else
			echo
        	        echo -e "\t\t\e[31mPlease input the right number.\e[0m"
               		read

		fi
		;;
	2)
		bash scripts/log.sh
		;;
	3)
		;;
	Q|q)
		echo
		echo -e "\t\t\t\t\e[34mTHANKS,BYE!\e[0m"
		echo
		exit 0
		;;
	*)
		echo
		echo -e "\t\t\e[31mPlease input the right number.\e[0m"
		read
		;;
	esac
done
